from typing import Any, Protocol


class RuntimeContextProtocol(Protocol):
    def get(self, key: str) -> Any: ...
    def has(self, key: str) -> bool: ...
    def set(self, key: str, value: Any) -> None: ...


class StrategyStepConfigProtocol(Protocol):
    def get(self, key: str) -> Any: ...
    def has(self, key: str) -> bool: ...
