# configs/strategy/_steps/strategy_steps.yaml

# YAML Structure Explanation:
# Matches the model definition in core/strategy/steps/model.py `StrategyStepDefinition`
# - input_bindings:
#     - Keys are the parameter names expected by the function
#     - Each value includes:
#         - source: either "runtime" (from context) or "config" (from static config)
#         - mapping: the key to look up in that source
# - output_bindings:
#     - Keys are the keys returned by the function
#     - Each value includes:
#         - mapping: target name in context, or "_" to return directly
# - config_bindings (optional):
#     - Keys are the parameter names expected by the function
#     - Values are config keys to resolve from static config

- id: detect_trend
  function: "src.utils.get_trend"
  input_bindings: {}
  output_bindings:
    trend:
      mapping: "_"

- id: find_extreme
  function: "src.utils.is_extreme_bar"
  input_bindings:
    trend:
      source: runtime
      mapping: "trend"
  output_bindings:
    is_extreme:
      mapping: "_"

- id: validate_pullback
  function: "src.utils.is_bars_since_extreme_pivot_valid"
  input_bindings:
    major_swing_high_idx:
      source: runtime
      mapping: "extreme_bar_index"
  output_bindings:
    bars_valid:
      mapping: "_"

- id: check_fib
  function: "src.utils.is_within_fib_extension"
  input_bindings:
    trend:
      source: runtime
      mapping: "trend"
    ref_swing_start_idx:
      source: runtime
      mapping: "bar_index_start"
    ref_swing_end_idx:
      source: runtime
      mapping: "bar_index_end"
  output_bindings:
    fib_valid:
      mapping: "_"

- id: detect_wrb
  function: "src.steps.technical.wrb.detect_wide_range_bar"
  input_bindings: {}
  output_bindings:
    strategy_wrb_detected_wide_range_bar:
      mapping: "_"
  config_bindings:
    lookback_bars: "lookback_bars"
    min_size_increase_dec: "min_size_increase_dec"