name: "Trend Following Strategy"
steps:
  - id: detect_trend
    description: "Determine the current market trend direction"
    config_bindings: {}
    runtime_bindings: {}

  - id: find_extreme
    description: "Identify extreme pivot points in the trend"
    config_bindings: {}
    runtime_bindings:
      trend: "trend"

  - id: validate_pullback
    description: "Check if pullback meets criteria"
    config_bindings: {}
    runtime_bindings:
      major_swing_high_idx: "extreme_bar_index"

  - id: check_fib
    description: "Verify if price action meets Fibonacci extension criteria"
    config_bindings: {}
    runtime_bindings:
      trend: "trend"
      ref_swing_start_idx: "bar_index_start"
      ref_swing_end_idx: "bar_index_end"
    reevaluates:
      - validate_pullback