name: "Day Trading Session"
description: "High-frequency trading session for intraday strategies"

# Portfolio reference
portfolio: "main-portfolio"
capital_allocation: 30000.00

# Symbol mapping - connects strategies to providers
symbols:
  AAPL:
    strategy: "sample_strategy"
    providers:
      data: "csv"
      execution: "file"  # Using file as execution provider
    timeframe: "5m"
    enabled: true
  
  SPY:
    strategy: "sample_strategy"
    providers:
      data: "yahoo"
      execution: "file"  # Using file as execution provider
    timeframe: "1d"
    enabled: true