name: "Day Trading Session"
description: "High-frequency trading session for intraday strategies"

# Portfolio reference
portfolio: "main-portfolio"
capital_allocation: 30000.00

# Symbol mapping - connects strategies to providers
symbols:
  AAPL:
    providers:
      data: "csv"
      execution: "csv"  # Using csv as execution provider temporarily
    timeframe: "5m"
    enabled: true
  
  SPY:
    providers:
      data: "yahoo"
      execution: "yahoo"  # Using yahoo as execution provider temporarily
    timeframe: "1d"
    enabled: true