# Price Feed Configuration
# This file defines settings for different price feed providers

# Yahoo Finance settings
yahoo:
  cache:
    duration: "1h"            # How long to cache price data
    max_size: "1GB"           # Maximum cache size
    cleanup_interval: "1d"    # How often to clean up old cache entries
  
  rate_limits:
    requests_per_minute: 60   # Maximum requests per minute
    requests_per_day: 2000    # Maximum requests per day
    retry_delay: 5            # Seconds to wait between retries
  
  data_quality:
    min_bars: 100            # Minimum number of bars required
    max_gap: 3               # Maximum allowed gap in days
    required_fields:         # Required fields in price data
      - "Open"
      - "High"
      - "Low"
      - "Close"
      - "Volume"
  
  supported_timeframes:
    - "1d"                   # Daily
    - "1w"                   # Weekly

# Future providers can be added here
# Example:
# alpha_vantage:
#   cache:
#     duration: "15m"
#     max_size: "500MB"
#   rate_limits:
#     requests_per_minute: 5
#     requests_per_day: 500 

price_feeds:
  csv:
    name: csv
    timeframes:
      supported_timeframes:
        - "1m"    # 1 minute
        - "2m"    # 2 minutes
        - "3m"    # 3 minutes
        - "5m"    # 5 minutes
        - "7m"    # 7 minutes
        - "10m"   # 10 minutes
        - "15m"   # 15 minutes
        - "20m"   # 20 minutes
        - "30m"   # 30 minutes
        - "1h"    # 1 hour
        - "2h"    # 2 hours
        - "4h"    # 4 hours
        - "1d"    # 1 day
      native_timeframe: "1m"  # The finest granularity available in the data
      resample_strategy:
        open: first
        high: max
        low: min
        close: last
        volume: sum
    provider_config:
      data_dir: tests/data
      file_pattern: "*.csv"
      date_format: "%Y-%m-%d %H:%M:%S"

  yahoo:
    name: yahoo
    timeframes:
      supported_timeframes:
        - "1d"    # Daily
        - "1w"    # Weekly
      native_timeframe: "1d"  # Yahoo Finance provides daily data
      resample_strategy:
        open: first
        high: max
        low: min
        close: last
        volume: sum
    provider_config:
      api_key: "${YAHOO_API_KEY}"  # Load from environment variable
      cache_duration: "1h"
      rate_limits:
        requests_per_minute: 2000
        requests_per_day: 100000 