# Risk Management Configuration
# This file defines reusable risk management parameters

# Default risk limits for portfolios
default_risk_limits:
  max_position_size: 10000.00  # Maximum position size in base currency
  max_drawdown: 0.10          # Maximum drawdown allowed (10%)
  stop_loss_pct: 0.02         # Default stop loss percentage (2%)
  take_profit_pct: 0.04       # Default take profit percentage (4%)

# Position sizing rules
position_sizing:
  max_risk_per_trade: 0.01    # Maximum risk per trade (1% of portfolio)
  max_correlation: 0.7        # Maximum correlation between positions
  max_sector_exposure: 0.25   # Maximum exposure to a single sector (25%)

# Portfolio constraints
portfolio_constraints:
  max_leverage: 1.0           # Maximum allowed leverage
  min_liquidity: 1000000      # Minimum daily trading volume
  max_slippage: 0.001        # Maximum allowed slippage (0.1%)

# Risk monitoring
risk_monitoring:
  check_interval: "1h"        # How often to check risk limits
  alert_threshold: 0.8        # Alert when approaching limits (80%)
  max_open_positions: 10      # Maximum number of open positions 