# Trading System Configuration
# This shows how to configure the trading system components

# Price Feed Configuration
price_feeds:
  yahoo:
    provider: "yahoo"
    config:
      api_key: "${YAHOO_API_KEY}"  # Load from environment variable
      cache_duration: "1h"
      supported_timeframes:
        - "1d"
        - "1w"

# Portfolio Configuration
portfolio:
  name: "Main Portfolio"
  initial_capital: 100000.00
  risk_limits:
    max_position_size: 10000.00
    max_drawdown: 0.10
    stop_loss_pct: 0.02
    take_profit_pct: 0.04

# Trading Session Configuration
trading_sessions:
  main_session:
    name: "Main Trading Session"
    symbols:
      AAPL:
        symbol: "AAPL"
        price_feed: "yahoo"
        timeframe: "1d"
        feed_config:
          cache_duration: "1h"
      MSFT:
        symbol: "MSFT"
        price_feed: "yahoo"
        timeframe: "1d"
        feed_config:
          cache_duration: "1h"
    portfolio: "Main Portfolio"
    price_feeds:
      - "yahoo"

# Strategy Configuration
strategies:
  trend_following:
    name: "Trend Following Strategy"
    session: "main_session"
    symbols:
      - "AAPL"
      - "MSFT"
    steps:
      - system_step_id: detect_trend
        description: "Determine the current market trend direction"
        static_config: {}
        dynamic_config: {}
      - system_step_id: find_extreme
        description: "Identify extreme pivot points in the trend"
        static_config: {}
        dynamic_config:
          trend: "trend"
      - system_step_id: validate_pullback
        description: "Check if pullback meets criteria"
        static_config: {}
        dynamic_config:
          major_swing_high_idx: "extreme_bar_index"
      - system_step_id: check_fib
        description: "Verify if price action meets Fibonacci extension criteria"
        static_config: {}
        dynamic_config:
          trend: "trend"
          ref_swing_start_idx: "bar_index_start"
          ref_swing_end_idx: "bar_index_end"
        reevaluates:
          - validate_pullback 